version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: blog-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone

  minio:
    image: minio/minio
    container_name: blog-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data:
