jwt:
  secret: YourSuperSecretKeyForJWTTokenGeneration2026BlogSystem

server:
  port: 9090

spring:
  application:
    name: supergaos-gateway
  config:
    import: optional:nacos:  # Required by Spring Cloud Alibaba 2023.x
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        namespace: supergaos
        file-extension: yml
        shared-configs:
          - data-id: gateway.yml
            refresh: true
    gateway:
      routes:
        - id: blog-service
          uri: lb://supergaos-blog
          predicates:
            - Path=/api/blog/**
        - id: comment-service
          uri: lb://supergaos-comment
          predicates:
            - Path=/api/comment/**
        - id: file-service
          uri: lb://supergaos-file
          predicates:
            - Path=/api/file/**
        - id: user-service
          uri: lb://supergaos-user
          predicates:
            - Path=/api/user/**

